# Alabaster Light theme for WezTerm

[colors]
ansi = ['#000000', '#AA3731', '#448C27', '#9A6515', '#325CC0', '#811abc', '#4078a0', '#f5f5f5']
brights = ['#777777', '#c04038', '#5da03a', '#b8860b', '#4a78d0', '#9932cc', '#5090b0', '#ffffff']
background = '#f5f5f5'
foreground = '#000000'
cursor_bg = '#000000'
cursor_border = '#000000'
cursor_fg = '#f5f5f5'
selection_bg = '#325CC0'
selection_fg = '#000000'

[colors.indexed]

[metadata]
name = 'Alabaster Light'
